name: Build Project

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: joonatanaatos
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Lint
        run: yarn lint
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joonatanaatos/website:${{ env.BRANCH_NAME }}
      - name: Push Docker image with latest tag
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joonatanaatos/website:latest
        if: github.ref == 'refs/heads/main'
